"""Build the standalone Windows application with PyInstaller.

Run it with the minimal build environment (see README), so that only the
libraries the application really needs are bundled:

    build\\venv\\Scripts\\python tools/build_exe.py            # both variants
    build\\venv\\Scripts\\python tools/build_exe.py --mode onefile

Variants (both open only the application window - no console):
  onefile  dist/FSOC_Simulator.exe
           one file; unpacks itself to a temporary folder on EVERY start,
           so it opens more slowly.
  onedir   dist/FSOC_Simulator/FSOC_Simulator.exe (+ an _internal folder)
           opens fastest - nothing to unpack. Share it as a zip.

Performance reports are written to a `runs` folder next to the .exe.
Bundled: config/, scenarios/, the CNN model, fsoc/assets (plotly.js for the
HTML report). Unused parts of Qt / OpenCV are filtered out.
"""

import argparse
import shutil
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EXCLUDES = ["torch", "torchvision", "sklearn", "scipy", "tensorflow", "pandas", "plotly", "IPython",
            "jupyter", "notebook", "tkinter", "PyQt5", "PyQt6", "PySide2", "onnx", "onnxruntime",
            "numba", "sympy", "skimage", "ultralytics", "statsmodels", "sqlalchemy", "pyarrow",
            "altair", "yt_dlp", "zmq", "lxml", "jinja2", "cryptography", "av", "imageio", "pytest",
            "rich", "pydantic", "websockets", "shapely", "win32com", "pythoncom", "debugpy", "pydevd",
            "PySide6.QtNetwork", "PySide6.QtQml", "PySide6.QtQuick", "PySide6.QtPdf", "PySide6.QtTest",
            "PySide6.QtWebEngineCore", "PySide6.QtMultimedia", "PySide6.QtSql"]

# Files dropped from the bundle (substring match on the destination path).
DROP = ["opencv_videoio_ffmpeg",          # video codecs - the app only processes frames
        "Qt6Quick", "Qt6Qml", "Qt6Pdf", "Qt6VirtualKeyboard", "Qt6Network", "Qt6Test",
        "PySide6\\translations", "PySide6/translations", "\\qml\\", "/qml/",
        "mpl-data\\sample_data", "mpl-data/sample_data"]

SPEC = r'''
# Generated by tools/build_exe.py - do not edit by hand.
import sys
ROOT = r"{root}"
MODE = "{mode}"
DROP = {drop!r}

a = Analysis(
    [ROOT + r"\app.py"],
    pathex=[ROOT],
    datas=[(ROOT + r"\config", "config"), (ROOT + r"\scenarios", "scenarios"),
           (ROOT + r"\models\beacon_cnn.onnx", "models"), (ROOT + r"\fsoc\assets", r"fsoc\assets")],
    hiddenimports=["pyqtgraph.opengl", "OpenGL.platform.win32", "fsoc.report",
                   "matplotlib.backends.backend_agg", "mpl_toolkits.mplot3d"],
    excludes={excludes!r},
    noarchive=False,
)
keep = lambda entry: not any(p in entry[0] for p in DROP)
a.binaries = [b for b in a.binaries if keep(b)]
a.datas = [d for d in a.datas if keep(d)]
pyz = PYZ(a.pure)
if MODE == "onefile":
    exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name="FSOC_Simulator",
              console=False, upx=False, runtime_tmpdir=None)
else:
    exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name="FSOC_Simulator", console=False, upx=False)
    coll = COLLECT(exe, a.binaries, a.datas, name="FSOC_Simulator", upx=False)
'''


def build(mode):
    import PyInstaller.__main__
    spec = ROOT / "build" / f"fsoc_{mode}.spec"
    spec.parent.mkdir(exist_ok=True)
    spec.write_text(SPEC.format(root=str(ROOT), mode=mode, drop=DROP, excludes=EXCLUDES), encoding="utf-8")
    t0 = time.time()
    PyInstaller.__main__.run([str(spec), "--noconfirm", "--clean",
                              "--distpath", str(ROOT / "dist"), "--workpath", str(ROOT / "build" / f"work_{mode}")])
    target = ROOT / "dist" / ("FSOC_Simulator.exe" if mode == "onefile" else "FSOC_Simulator")
    size = target.stat().st_size if target.is_file() else sum(p.stat().st_size for p in target.rglob("*") if p.is_file())
    print(f"\n[{mode}] built {target}  ({size / 1e6:.0f} MB) in {time.time() - t0:.0f} s")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--mode", choices=["onefile", "onedir", "both"], default="both")
    args = p.parse_args()
    if "venv" not in sys.executable:
        print("NOTE: not running from build\\venv - the bundle may include unrelated libraries "
              "installed on this machine and be much larger.")
    shutil.rmtree(ROOT / "dist", ignore_errors=True)
    for mode in (["onedir", "onefile"] if args.mode == "both" else [args.mode]):
        build(mode)


if __name__ == "__main__":
    main()
